### ISSUE TITLE
[Plugin request] Crafting

### ISSUE THREAD

**Issue by smt923** [tltneon/nutscript_plugins#4]
Another plugin that'd be nice to have, if that's not too much to ask (I know ModernRP has a crafting, but it seems incomplete or unfinished, I don't really know enough lua to make that work my self)

https://www.sendspace.com/file/g97us9

I moved some of the nut.add.Lang stuff to the new sh_languages format thing already, to cut out at least a little tedious work - at least I think, anyway

``` lua
crafting = "Crafting",
craftingtable = "Crafting Table",
req_moremat = "You need more materials to craft %s.",
req_blueprint = "You need a blueprint of %s to craft %s.",
req_morespace  = "You need more space to get result.",
donecrafting = "You have crafted %s.",
icat_material = "Materials",
craft_menu_tip1 = "You can craft items by clicking the icons in the list.",
craft_menu_tip2 = "The icon with book means that item needs a blueprint to be crafted.",
crft_text =  "Crafting %s\n%s\n\nRequirements:\n"
```

**Comment by tltneon** [comment]
Check out repo: https://github.com/tltneon/nutscript_plugins/tree/ns-1.1/plugins/crafting

P.S. Thanks for the archive and cutted lines ;)
