### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by fulltimehobo** [tltneon/nutscript_plugins#5]
[ERROR] gamemodes/hl2rp/plugins/crafting/sh_menu.lua:151: bad argument #1 to 'Simple' (number expected, got nil)
1. Simple - [C]:-1
   1. DoClick - gamemodes/hl2rp/plugins/crafting/sh_menu.lua:151
   2. unknown - lua/vgui/dlabel.lua:218
      when I try to click an item in the crafting table

**Comment by tltneon** [comment]
Try out now. And don't forget to download these plugin https://github.com/tltneon/nsplugins/tree/ns-1.1/plugins/_oldplugins-fix
