### ISSUE TITLE
World Item Spawner

### ISSUE THREAD

**Issue by farman-beep** [tltneon/nutscript_plugins#8]
I tried to use this plugin in game, but its broken i believe. I set a item spawn point and it kept spawning items ontop of each other. I even set the items per spawn to 1 but it still did not work!

Please help!

**Comment by tltneon** [comment]
I need more detail to understand what the problem is.

**Comment by farman-beep** [comment]
Currently I believe its fixed, the plugin broke because I had Black Tea's css weapon based added on.

**Comment by farman-beep** [comment]
I was incorrect, this plugin is completely broken. It keeps spawning items in one spawn on top of each other causing a lot of lag in the server. In detail, there is no function in the script that checks if theres an entity already valid and if there is it wont spawn another one on top when spawntime > CurTime().
